### ISSUE TITLE
How to run program as admin?

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [lifenjoiner/sendto-plus#1]
Thanks for creating such a useful utility! Some tools are more useful when being executed as administrator. For example, Process Explorer, only when run as admin and you can see all system processes. I want to know if it's possible to run a program as admin when using sendto-plus? Thanks.

**Comment by lifenjoiner** [comment]
Sure. You can set that from the `Properties` -> `Compatibility` -> `Run this program as an administrator`:
![RunAsAdmin](https://user-images.githubusercontent.com/19585474/146623871-4c054f0f-4582-4e93-89c6-e83d5b1f874c.png)

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thanks for the tip. I tried and it works well. I should have thought of that.
