### ISSUE TITLE
Can you support the new right-click menu of Win11?

### ISSUE THREAD

**Issue by PandaFiredoge** [lifenjoiner/sendto-plus#2]

**Comment by lifenjoiner** [comment]
If you are saying the new menu is too [poor of functionality that hiding sendto](https://answers.microsoft.com/en-us/windows/forum/all/restore-old-right-click-context-menu-in-windows-11/a62e797c-eaf3-411b-aeec-e460e6e5a82a) and other items, I'm afraid no.
As the readme says: sendto+ doesn't modify any file or process of the system.

Win11 is psycho and buggy. Not practical, but just fancy.
There are other awesome apps that can restore the classic right-click menu.
